### ISSUE TITLE
Feature request : Lines wrapping

### ISSUE THREAD

**Issue by omasseau** [nickbnf/glogg#233] opened 2018-07-19 09:12 UTC
It would be really nice to have an option for lines wrapping.
It is a bit annoying to have to scroll horizontally when a line is too long to fit the window ;)

**Comment by negora** [comment] 2018-07-21 08:40
I think that it's a duplicate of #206 . But I agree, this feature would make a BIG difference. It's the only feature that I'm missing right now.

**Comment by nickbnf** [comment] 2018-08-05 19:33
Closed as duplicate of #206

**Closed by nickbnf** 2018-08-05 19:33 UTC
