### ISSUE TITLE
Mass output of "QFile::open: File (/path/to/file) already open"

### ISSUE THREAD

**Issue by anthonybilinski** [nickbnf/glogg#181] opened 2017-10-03 00:35 UTC
I've compiled locally off hash 6f5eaa808c6ed209d74f765babf09ca24d22e06b

After opening glogg from command line, I see 100s of the Qt error message over the course of a couple hours.

I'm using search with extended regexp, following file, and the file is being written to but not moved or anything. There is no observable behaviour problem.

**Comment by bradx954** [comment] 2017-10-13 17:47
Can confirm I have this exact same issue with version "1.1.0-1+b2" in debian 9. Seems to happen after being open for about 30 seconds.

**Comment by thehomerepot** [comment] 2018-03-09 18:06
Same issue on both stable 1.1.4 and the latest from git master. All I do is select "Follow file" and it starts happening.

**Comment by sergei-dyshel** [comment] 2018-05-29 18:00
Probably caused by https://github.com/nickbnf/glogg/commit/2686d8e51c39a61a0e1014dc41717bacb2c2918a: file gets reopened each time `mtime` changes which causes Qt to add emit journal/syslog message.

**Comment by nickbnf** [comment] 2018-08-13 13:31
Should be fixed by 9f850936f193b6e0057829e50d76cbf76e3a62c7. Please reopen if not.

**Closed by nickbnf** 2018-08-13 13:31 UTC
