### ISSUE TITLE
Follow File not working

### ISSUE THREAD

**Issue by jlanzarotta** [nickbnf/glogg#114] opened 2016-05-20 16:15 UTC
Hello,

I am looking for a log viewer that can handle very large files and I found glogg.  Everything is good except that the "Follow File" is not working on Windows 7 x64 using the latest version of the software.

As a log file grows, no new long show up unless I do an actual reload of the file.  I know the file is growing because I can use plain ol' "tail -f" to see that the file is indeed growing...

Any ideas?

Thanks,

**Comment by jlanzarotta** [comment] 2016-05-26 19:56
I am attempting to build on debian 8.  Having issues with virtualbox...

Anyways, it seems to work "sometimes" but then stops working.

**Comment by jlanzarotta** [comment] 2016-06-02 12:33
Well, I have not got the Win32 build to work under Debian. :(

Anyways, does anyone have a clue on why glogg is not able to determine that a logback log has been updated on Windows?

**Comment by artesa** [comment] 2016-06-07 15:36
I'm facing the same issue. I use glogg to view Android logcat, printed out to a file, on Windows 7 x64.

It works perfectly on Linux (that's how I know this app), and I've found no better option for Windows so far. But unfortunately absence of this crucial feature messes all up.

The new feature "scroll to update" does not work either, I need to manually press "Reload" button to update the content. It happens all the time while logcat is printing something out to the target file. When, however, I stop logcat, content, apparently, is automatically refreshed.
May it be some issue with multiprocess synchronization?..

**Comment by jlanzarotta** [comment] 2016-06-08 12:14
If I could get the code to compile successfully, I might have a change to debug it.  Unfortunately for me, the program is unfortunately unusable on Windows with the "follow" working...

**Comment by pinonpierre** [comment] 2016-07-11 13:23
Same issue on Windows 10 x64.
Do you have some news about this problem ?

**Comment by jlanzarotta** [comment] 2016-07-13 12:40
Nope.  I would love to use this program since it is cross-platform as well as open-source.  However, I need a working solution and have moved on for now.  I might return if the original author would give us a clue as to what is going on...

**Comment by nickbnf** [comment] 2017-03-21 16:03
Closed as a duplicate of #65.

**Closed by nickbnf** 2017-03-21 16:03 UTC
