### ISSUE TITLE
Drag and Drop on Windows 10 Pro does not work correctly

### ISSUE THREAD

**Issue by shvez** [nickbnf/glogg#209] opened 2018-02-02 10:07 UTC
Hi, there.

Good and promising work. Currently i'm using Baretail pro.  but this soft also looks very good.

during try to use of version 1.1.4-x86-64 i found that when i drag and drop file to window not all files are opened. I had one file already opened. then i selected in folder already opened file and two other files. after dropping them to window one file was not opened by viewer.

best,
ilya

**Comment by evandrocoan** [comment] 2018-02-02 15:17
You can try use @varia's fork on https://github.com/variar/klogg, he did several updates on the last year.

I also used Baretail, but glogg performance was much better on my slow computer.

**Comment by nickbnf** [comment] 2018-02-13 14:48
Where is it fixed on klogg? Isn't it a duplicate of #182 ?

**Comment by shvez** [comment] 2018-02-14 06:29
It is not fixxed in klogg
and i do not think it is duplicating this issue.  Drag&Drop works for one file, but does not work for many.  Probably you did not expect that someone will drag many files

best,
ilya

**Comment by nickbnf** [comment] 2018-02-14 08:50
OK, yes multiple files is not implemented, I'll look into it.

**Comment by nickbnf** [comment] 2018-06-18 14:21
Anton's commit should have fixed this.

**Closed by nickbnf** 2018-06-18 14:21 UTC
