### ISSUE TITLE
Error: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by jlanzarotta** [nickbnf/glogg#154] opened 2017-05-11 17:51 UTC
Hello,

If for example, I have a log file open in glogg and the log file rolls over at midnight, I get an exception saying that my application cannot access the log file because it is being used by another process...

Any ideas?  Thanks.

**Comment by jlanzarotta** [comment] 2017-05-15 20:16
Anyone else seeing this sort of thing happen to them?

**Comment by variar** [comment] 2017-05-18 09:27
Hi, see #109. File is kept open by glogg for performance reasons

**Comment by nickbnf** [comment] 2017-05-19 13:56
Yep, closed as a duplicate of #109.

**Closed by nickbnf** 2017-05-19 13:56 UTC
